---
nameOverride: ""
fullnameOverride: ""

namespace: argocd
k8s_sync: true

admin:
  enable: true

all_app_get: false

account:
- name: alice
  enable: true
  capabilities:
    login: true
    apikey: true
  project:
  - namespace1
- name: greg
  admin: true
  enable: true
  capabilities:
    login: true
    apikey: false
  project:
  - namespace1
  - namespace2

project:
- name: namespace1
  template: true
### When you try to set it manually, delete the comment below and set the template to false. ###
# description: namespace1 kubernetes namespace
# sourceRepos:
# - '*'
# destinations:
# - namespace: namespace1
#   server: https://kubernetes.default.svc
# clusterResourceWhitelist:
# - group: '*'
#   kind: 'PersistentVolume'
# clusterResourceBlacklist:
# - group: '*'
#   kind: Namespace
# - group: '*'
#   kind: RoleBinding
# - group: '*'
#   kind: ClusterRoleBinding
- name: namespace2
  template: true