---
nameOverride: ""
fullnameOverride: ""

namespace: argocd

admin:
  enable: false

account:
- name: alice
  enable: true
  capabilities:
    login: true
    apikey: true
  project:
  - project1
- name: greg
  admin: true
  enable: true
  capabilities:
    login: true
    apikey: false
  project:
  - project1
  - project2
