{{- if .Values.k8s_sync }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-cluster-admin
  namespace: default
roleRef:
  kind: ClusterRole
  name: k8s-cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
{{- range .Values.account }}
{{- if .admin }}
- kind: ServiceAccount
  name: {{ .name }}
  namespace: default
{{- end }}{{ end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-cluster-admin
  labels: {{ include "argocd-account.labels" . | nindent 4 }}
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["*"]
{{- end }}