{{- if .Values.k8s_sync }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-cluster
  namespace: default
  labels: {{ include "argocd-account.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: k8s-cluster
  apiGroup: rbac.authorization.k8s.io
subjects:
{{- range .Values.account }}
- kind: ServiceAccount
  name: {{ .name }}
  namespace: default
{{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-cluster
  labels: {{ include "argocd-account.labels" . | nindent 4 }}
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["*"]
{{- end }}